name: Therapywriter
favicon: null
layout_spectrum: 0.45216577872633934
typography_spectrum: 0.7685315739363432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0f0e'
    - '#ffffff'
    - '#74aaf4'
    - '#9fd8ff'
    - '#495725'
  brandStrength: 0.6151813671458513
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
